site_name: Pulse
site_description: Arduino Ultrasonic Parking Sensor

repo_name: tvcsantos/pulse
repo_url: https://github.com/tvcsantos/pulse
edit_uri: blob/master/docs/

copyright: Copyright 2021 Tiago Santos

theme:
  name: material
  logo: img/icon_mac_light.png
  palette:
    primary: teal
    accent: orange

markdown_extensions:
  - attr_list
  - md_in_html
